# epoch-template
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  labels:
    name: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      name: front-end
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
      - name: front-end
        image: 10.197.17.180:5000/epochdemo/demo_frontend_image:2.0.0-03181811
        ports:
        - containerPort: 8000
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8000
  selector:
    name: front-end